Update pom.xml
Snyk updated the databind version https://github.com/fullstorydev/solr-bench/commit/627b22ebbd05e6227257ba12eb62485b7813042c of jackson-databind but not the jackson-core.

That leads to runtime exception
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:656)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at org.apache.solr.benchmarks.BenchmarksMain.main(BenchmarksMain.java:98)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
```

Bumping the jackson-core version to match